services:
  web:
    build: .
    image: gitnoc
    container_name: gitnoc_web
    environment:
      GITNOC_REDIS_HOST: redis
    command: python manage.py server-prod
    ports:
    - "5050:5050"
    volumes:
    - .:/gitnoc
    depends_on:
      redis:
        condition: service_healthy
  worker:
    build: .
    image: gitnoc
    container_name: gitnoc_worker
    environment:
      GITNOC_REDIS_HOST: redis
    command: python manage.py runworker
    volumes:
    - .:/gitnoc
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
