version: '2'
services:
  web:
    build: .
    image: gitnoc
    container_name: gitnoc_web
    environment:
      LOCAL_SETTINGS: /gitnoc/settings.cfg
    command: python manage.py server-prod
    ports:
    - "5050:5050"
    volumes:
    - .:/gitnoc
    depends_on:
    - redis
  worker:
    image: gitnoc
    container_name: gitnoc_worker
    environment:
      LOCAL_SETTINGS: /gitnoc/settings.cfg
    command: python manage.py runworker
    volumes:
    - .:/gitnoc
    depends_on:
    - redis
  redis:
    image: redis:3.2